/*
 * STRAFE 64 license public key -- GENERATED by tools/keygen/keygen.py.
 * Do NOT edit by hand. Regenerate with: keygen.py export-pubkey-c
 *
 * This is the public half of the Ed25519 keypair. It is safe to ship; it
 * can only *verify* keys, never mint them.
 */
#ifndef LICENSE_PUBKEY_H
#define LICENSE_PUBKEY_H

#define LICENSE_PUBKEY_LEN 32

static const unsigned char license_public_key[LICENSE_PUBKEY_LEN] = {
	0x77, 0xc9, 0x57, 0x33, 0xef, 0x38, 0xc8, 0x55,
	0xb5, 0xbb, 0x00, 0x60, 0xb5, 0x71, 0x27, 0xaa,
	0xb9, 0xf9, 0x4d, 0x08, 0x91, 0xd3, 0x25, 0xfc,
	0x80, 0xe5, 0xf7, 0xa1, 0x1b, 0x08, 0x24, 0xa4,
};

#endif /* LICENSE_PUBKEY_H */
