#!/usr/bin/env python3
"""STRAFE 64 license-key generator.

Mints Ed25519-signed license keys you can sell, and mirrors the in-engine
verifier so you can validate a key from support tickets. The private signing
key never leaves this machine; the engine ships only the matching public key.

Quick start
-----------
    python3 keygen.py init                      # one-time: create the keypair
    python3 keygen.py export-pubkey-c           # write pubkey header for engine
    python3 keygen.py mint --tier standard -n 50 --out batch.txt
    python3 keygen.py verify S64-XXXXXX-...      # check a key

Files (all under tools/keygen/, git-ignored):
    keys/strafe64_private.key   base64 Ed25519 seed  -- SECRET, back this up
    keys/strafe64_public.key    base64 public key
    ledger.csv                  every key ever minted
"""

from __future__ import annotations

import argparse
import base64
import csv
import datetime as dt
import secrets
import sys
from pathlib import Path

try:
    from nacl.signing import SigningKey, VerifyKey
    from nacl.exceptions import BadSignatureError
except ImportError:
    sys.exit("error: PyNaCl is required (pip install pynacl)")

import license_format as fmt

HERE = Path(__file__).resolve().parent
KEYS_DIR = HERE / "keys"
PRIVATE_PATH = KEYS_DIR / "strafe64_private.key"
PUBLIC_PATH = KEYS_DIR / "strafe64_public.key"
LEDGER_PATH = HERE / "ledger.csv"
PUBKEY_HEADER = (
    HERE.parent.parent / "engine" / "code" / "qcommon" / "license_pubkey.h"
)
LEDGER_FIELDS = ["serial", "tier", "tier_name", "issue", "key", "buyer", "note", "minted_at"]


# --------------------------------------------------------------------------- keys
def load_signing_key() -> SigningKey:
    if not PRIVATE_PATH.exists():
        sys.exit("error: no private key. Run 'keygen.py init' first.")
    seed = base64.b64decode(PRIVATE_PATH.read_text().strip())
    return SigningKey(seed)


def load_verify_key() -> VerifyKey:
    if PUBLIC_PATH.exists():
        return VerifyKey(base64.b64decode(PUBLIC_PATH.read_text().strip()))
    return load_signing_key().verify_key


def cmd_init(args: argparse.Namespace) -> None:
    KEYS_DIR.mkdir(parents=True, exist_ok=True)
    if PRIVATE_PATH.exists() and not args.force:
        sys.exit(
            f"error: {PRIVATE_PATH} already exists. Refusing to overwrite "
            "(this would invalidate every key you've sold). Use --force only "
            "if you are certain."
        )
    sk = SigningKey.generate()
    PRIVATE_PATH.write_text(base64.b64encode(bytes(sk)).decode() + "\n")
    PRIVATE_PATH.chmod(0o600)
    PUBLIC_PATH.write_text(base64.b64encode(bytes(sk.verify_key)).decode() + "\n")
    print(f"wrote {PRIVATE_PATH}  (SECRET -- back this up offline)")
    print(f"wrote {PUBLIC_PATH}")
    print("next: run 'keygen.py export-pubkey-c' then rebuild the engine.")


def cmd_export_pubkey_c(args: argparse.Namespace) -> None:
    pub = bytes(load_verify_key())
    rows = []
    for i in range(0, len(pub), 8):
        chunk = ", ".join(f"0x{b:02x}" for b in pub[i:i + 8])
        rows.append("\t" + chunk + ",")
    body = "\n".join(rows)
    header = f"""/*
 * STRAFE 64 license public key -- GENERATED by tools/keygen/keygen.py.
 * Do NOT edit by hand. Regenerate with: keygen.py export-pubkey-c
 *
 * This is the public half of the Ed25519 keypair. It is safe to ship; it
 * can only *verify* keys, never mint them.
 */
#ifndef LICENSE_PUBKEY_H
#define LICENSE_PUBKEY_H

#define LICENSE_PUBKEY_LEN 32

static const unsigned char license_public_key[LICENSE_PUBKEY_LEN] = {{
{body}
}};

#endif /* LICENSE_PUBKEY_H */
"""
    PUBKEY_HEADER.parent.mkdir(parents=True, exist_ok=True)
    PUBKEY_HEADER.write_text(header)
    print(f"wrote {PUBKEY_HEADER}")


# ------------------------------------------------------------------------- minting
def _mint_one(sk: SigningKey, tier: int, issue: dt.date) -> tuple[fmt.Payload, str]:
    serial = secrets.randbits(48) or 1
    payload = fmt.Payload(tier=tier, serial=serial, issue=issue)
    blob = bytes(sk.sign(payload.pack()))  # signature(64) || payload(12)
    assert len(blob) == fmt.BLOB_LEN, len(blob)
    return payload, fmt.format_key(blob)


def _append_ledger(records: list[dict]) -> None:
    exists = LEDGER_PATH.exists()
    with LEDGER_PATH.open("a", newline="") as f:
        w = csv.DictWriter(f, fieldnames=LEDGER_FIELDS)
        if not exists:
            w.writeheader()
        w.writerows(records)


def cmd_mint(args: argparse.Namespace) -> None:
    if args.tier not in fmt.TIERS:
        sys.exit(f"error: unknown tier {args.tier!r}. Choose from {', '.join(fmt.TIERS)}")
    tier_val = fmt.TIERS[args.tier]
    issue = dt.date.fromisoformat(args.issue) if args.issue else dt.date.today()
    now = dt.datetime.now(dt.timezone.utc).isoformat()
    sk = load_signing_key()

    keys, records = [], []
    for _ in range(args.count):
        payload, key = _mint_one(sk, tier_val, issue)
        keys.append(key)
        records.append({
            "serial": f"{payload.serial:012x}",
            "tier": tier_val,
            "tier_name": args.tier,
            "issue": issue.isoformat(),
            "key": key,
            "buyer": args.buyer or "",
            "note": args.note or "",
            "minted_at": now,
        })

    _append_ledger(records)
    text = "\n".join(keys) + "\n"
    if args.out:
        Path(args.out).write_text(text)
        print(f"minted {len(keys)} {args.tier} key(s) -> {args.out} (also logged to ledger.csv)")
    else:
        sys.stdout.write(text)
        print(f"# minted {len(keys)} {args.tier} key(s), logged to ledger.csv", file=sys.stderr)


# ------------------------------------------------------------------------- verify
def cmd_verify(args: argparse.Namespace) -> None:
    vk = load_verify_key()
    try:
        blob = fmt.parse_key(args.key)
    except ValueError as e:
        sys.exit(f"INVALID: malformed key ({e})")
    try:
        payload_bytes = vk.verify(blob)  # raises if signature is bad
    except BadSignatureError:
        sys.exit("INVALID: signature does not verify (forged or for a different keypair)")
    p = fmt.Payload.unpack(payload_bytes)
    if p.version != fmt.FORMAT_VERSION or p.product != fmt.PRODUCT_ID:
        sys.exit(f"INVALID: wrong version/product (v{p.version} product 0x{p.product:02x})")
    print("VALID")
    print(f"  tier   : {p.tier_name} ({p.tier})")
    print(f"  serial : {p.serial:012x}")
    print(f"  issued : {p.issue.isoformat()}")


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description="STRAFE 64 license-key generator")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("init", help="create the Ed25519 keypair (one time)")
    p.add_argument("--force", action="store_true", help="overwrite an existing keypair")
    p.set_defaults(func=cmd_init)

    p = sub.add_parser("export-pubkey-c", help="write license_pubkey.h for the engine")
    p.set_defaults(func=cmd_export_pubkey_c)

    p = sub.add_parser("mint", help="mint one or more keys")
    p.add_argument("--tier", default="standard", help=f"one of: {', '.join(fmt.TIERS)}")
    p.add_argument("-n", "--count", type=int, default=1, help="how many to mint")
    p.add_argument("--issue", help="issue date YYYY-MM-DD (default: today)")
    p.add_argument("--buyer", help="optional buyer tag recorded in the ledger")
    p.add_argument("--note", help="optional note recorded in the ledger")
    p.add_argument("--out", help="write keys to this file instead of stdout")
    p.set_defaults(func=cmd_mint)

    p = sub.add_parser("verify", help="verify a key string")
    p.add_argument("key", help="the license key to check")
    p.set_defaults(func=cmd_verify)

    args = ap.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
